### ISSUE TITLE
Task list before mid term report

### ISSUE THREAD

**Issue by Riiichan04** [Riiichan04/VietHomeAir#53]
## Việc cần làm trước khi báo cáo giữa kỳ
- [x] Config một web server sử dụng Django REST API dùng cho việc xử lý sentiment analysis
- [x] Thực hiện một model xử lý lọc các review spam hoặc review rác
- [ ] Cào data và xử lý cây quyết định để hiện thực cho phần đánh giá mô tả chủ nhà (optional)
- [ ] Đóng gói sentiment analysis và cho vào web dưới dạng một library (optional)

## Cần làm trong tối (23/12):
- [x] Hoàn thành trang kết quả tìm kiếm, danh mục
- [x] Hoàn thành phần web server chứa AI
- [x] Hoàn thành model spam filter

### Model
- [x] Chỉnh sửa csv để thông tin phù hợp với từng bảng trong db và thêm data vào db

### Service và View
- [x] Thực hiện xử lý business logic ở `servives`, truyền vào `view` và hiển thị lên `template`

#### Template
- [x] Hoàn thiện trang product @Riiichan04 
- [ ] Hoàn thiện trang quản lý của chủ bnb @Tran-3110 
- [ ] Hoàn thiện trang thông tin chủ bnb (phía người dùng) và  trang người dùng @NguyenLoan04 
- [ ] Hoàn thiện trang đăng ký làm chủ bnb và thêm bnb @NguyenHuuThinhNLU
